export const START_DATA = 'START_DATA';
export const SUCCESS_DISTRICTS = 'SUCCESS_DISTRICTS';
export const SUCCESS_COUNCIL_MEMBERS = 'SUCCESS_COUNCIL_MEMBERS';
export const SUCCESS_PARTICIPATORY_BUDGET_TRACKER = 'SUCCESS_PARTICIPATORY_BUDGET_TRACKER';
export const SUCCESS_PARTICIPATORY_BUDGET = 'SUCCESS_PARTICIPATORY_BUDGET';
export const FILTER_DATA = 'FILTER_DATA';
export const FAIL_DATA = 'FAIL_DATA';
export const MEMO_DISTRICTS_DATA = 'MEMO_DISTRICTS_DATA';

export const MOVE = 'MOVE';
export const CLICKED_ITEM = 'CLICKED_ITEM';
export const CLEAR_MAP_STATE = 'CLEAR_MAP_STATE';
export const CLICKED_DISTRICT_ID = 'CLICKED_DISTRICT_ID';
export const CLEAR_CLICKED_ITEM = 'CLEAR_CLICKED_ITEM';
export const CLICKED_DISTRICT_START = 'CLICKED_DISTRICT_START';
export const CLICKED_DISTRICT_SUCCESS = 'CLICKED_DISTRICT_SUCCESS';
export const CLICKED_DISTRICT_FAIL =  'CLICKED_DISTRICT_FAIL';
export const SET_MAP =  'SET_MAP';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_DISTRICT = 'UPDATE_DISTRICT';
export const UPDATE_YEAR = 'UPDATE_YEAR';
export const UPDATE_AGENCY = 'UPDATE_AGENCY';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const CLEAR_CONTROLS = 'CLEAR_CONTROLS';

export const CLICKED_ITEM_REDUCER = 'CLICKED_ITEM_REDUCER';
export const CLICKED_DISTRICT_REDUCER = 'CLICKED_DISTRICT_REDUCER';
export const CLEAR_CLICKED_DISTRICT_REDUCER = 'CLEAR_CLICKED_DISTRICT_REDUCER';
export const CLEAR_CLICKED_ITEM_REDUCER = 'CLEAR_CLICKED_ITEM_REDUCER';
export const ZOOM_REDUCER = 'ZOOM_REDUCER';